# Generated by Django 2.2.6 on 2020-03-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('0', 'like'), ('1', 'comment')], max_length=10)),
                ('at_person', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.Status')),
            ],
        ),
    ]
